### DISCUSSION TITLE
shell step: how to escape double qoutes

### DISCUSSION THREAD

**Discussion by kontramind** [pypyr/pypyr#253] [Q&A] [answered]
Hi,

How one can escape double quotes f.eks. to be able to call a command line path with space?

Many thanks
Aleksandar

**Comment by yaythomas** [comment, marked as answer]
Hi Aleksandar,

Any of the below should work, interchangeably:
```yaml
  - name: pypyr.steps.shell
    in:
      cmd: '"dir with space/file with space"'
  
  - name: pypyr.steps.shell
    in:
      cmd: '"dir with space"/"file with space"'

  - name: pypyr.steps.cmd
    in:
      cmd: ./"dir with space"/"file with space"
```

To explain what's going on here a bit more. . . To add the outside "extra" quote really is just because if the string _starts_ with a quote as the first character, yaml thinks this is a structural marking to indicate the start of a string. If you want to pass "extra" quotes to the underlying value you then put these inside the outside "yaml" quotes.

If the string value does NOT start with a quote, then you can actually just add the quotes you want to pass in the middle of the string and it's fine (like the last example).

As a final note. . . notice the difference between `pypyr.steps.shell` and `pypyr.steps.cmd` -  `shell` executes the sub-process by starting the system's default shell first, but you ONLY need this if you're actually using shell features like ~ expansion or | pipes. If you're just trying to execute a cmd like in the simplified examples I give here, you can just use `pypyr.steps.cmd` instead. But tt doesn't really matter, it's just a tiny bit more performant not to invoke the shell unless you actually need it. But I don't think it's anything a human eye is likely to notice :-)
