### DISCUSSION TITLE
Recording Pipeline activity with `ara`?

### DISCUSSION THREAD

**Discussion by blaisep** [pypyr/pypyr#280] [Ideas]
I just started using ara to record the results of playbook runs and I wonder if I could do something similar with pypyr?
https://blog.vkhitrin.com/analyzing-ansible-playbooks-using-ara/
https://ara.readthedocs.io/en/latest/

**Comment by yaythomas** [comment]
HI @blaisep, very interesting topic!

Short answer: no, pypyr doesn't have an out-of-box magic recorder in the same vein as _ara_. (That said, _ara_ is not an out-of-box bit of magic either, it need some setup/configuration.)

Longer answer: yes, there are various ways you can go about logging/recording pipeline runs.
1) At simplest, use the `--logpath` switch on the cli ([set_root_logger](https://pypyr.io/docs/api/run-pipeline/#set_root_logger-input-args) if you're using the api). This dumps whatever pypyr outputs to the file path specified. (`$ pypyr -h` to see CLI help)
2) You can configure your own python logging handler(s) using config - [configure pypyr logging](https://pypyr.io/docs/getting-started/config/#log_config). This uses the same logging handlers that python does - so you could theoretically fit any available python library/plug-in loggers (here are the stdlib ones - https://docs.python.org/3/library/logging.handlers.html) there to do what you want - structured logging etc.
3) The approaches outlined so far are just logging what pypyr outputs to logging & to the terminal. Especially when you're dealing with more "human readable" reports, the technical details of the logging output might not be what your report consumers are interested in. You might want to create a custom step to record points of interest where/how you want. 

```python
# mypackage/recorder.py

import my_db_api

def run_step(context):
    # okay this is obviously laughably simple, just to illustrate the point:
    # getting some values from context and passing them to whatever
    # logging/recording/db api or rest service you want
    
    # notice the get_formatted will make pypyr substitution expressions "just work"
    record = context.get_formatted('record')
    my_db_api.write(record)   
``` 

Details on [custom step creation](https://pypyr.io/docs/api/step/) here.

And then you can have pipelines like this, where the pipeline author explicitly uses the the `recorder` step to make an entry that your supervisors/non-techie personnel would be interested in, rather than swamp them with the more low-level technical log output:

```yaml
# ./my-pipeline.yaml
steps:
  - name: pypyr.steps.cmd
    in:
      cmd: ./mycmd --does important --things
        
  - name: mypackage.recorder
    in:
      record: "The mycmd sequence has run for the day"
       
  - name: pypyr.steps.cmd
    in:
      cmd:
        run: ./another-cmd --blah
        save: True
      
  - name: mypackage.recorder
    comment: only runs if returncode == 0 for previous cmd 
    skip: '{cmdOut.returncode}'
    in:
      # notice we're using a {substitution expression} here to format the recorder/log input
      record: "The another cmd process ran successfully with output: {cmdOut.stdout}" 
```

**Reply by blaisep-sureify** [reply]
`.recorder` brilliant, thank you.
I love the "points of interest" suggestion, thank you. In Ansible, the `name:` field is what appears in the console and in logs, so people sometimes make them descriptive. But every task is listed.
Recorder helps reduce the cognitive load.

**Comment by yaythomas** [comment]
ah, you remind me! Similarly, the `description` input in pypyr outputs to stdout.

So if you had:
```yaml
steps:
  - name: pypyr.steps.cmd
    description: -> 1. something descriptive here
    in:
      cmd: myprogram --blah

  - name: pypyr.steps.cmd
    description: -> 2. useful output here
    in:
      cmd: another-program --arg1 --arg2
```

You can then run it like this:
```console
$ pypyr my-pipeline
-> 1. something descriptive here
<<myprogram output here, if any>>
-> 2. useful output here
<<another-program output here, if any>>
```

So if you took the idea from 1) and 2) above - i.e 1) using pypyr with `--logpath` to capture the stdout output to file, or 2) using a custom python log formatter w `log_config` - you can capture all the stdout output into whatever log format you want.

i.e anything in `description` will end up in your log. I just added the text decoration like `-> 1.` in front to make it easier on the eye - but of course you can do what you want there. Also note that you can use `{formatting expressions}` in the `description` output, so you can dynamically tailor what goes to the logs/audit/reports.

(Note that for `cmd` & `shell` steps you can also suppress the program/shell statements stdout/stderr output if you want by redirecting to `/dev/null`, so what will end up in the output is _only_ the `description` field.

```yaml
- name: pypyr.steps.cmd
  description: this description will show up in output, but my-executable's output is suppressed
  in:
    cmd:
      run: ./my-executable --arg1 value
      stdout: /dev/null
```
)

Real world example:
I use `description` like this quite a lot to give myself a visual "progress indicator" or debugging aid. For example, pypyr uses pypyr to build itself with this pipeline https://github.com/pypyr/pypyr/blob/main/ops/build.yaml

Note the `description` field is used on certain notable/important steps - but not on "in-between" or "getting ready" sort of steps - there's no real science to this other than I'm only decorating steps that I find important "checkpoints" in the overall progress, but this is a matter of opinion, you can of course decorate whatever _you_ find important instead. I also just use the text decoration `-->` in front just as my own little convention to make them stand out in a busy log a bit more. 

When this pipeline runs as part of the GitHub action, you can see the output here: https://github.com/pypyr/pypyr/runs/6609819662?check_suite_focus=true (look under "Run build pipeline for linting, testing & package validation". The build output starts on line 62.

The `description` field is, if nothing else, nice supplementary information about what a particular command is actually doing - I find it helpful because when you're in the middle of a busy log like this, I find it useful to help anchor and orientate myself with what's happening when and in what sequence using these as prominent "road markers" if you will.

So hopefully between this, and the 3) custom step "recorder"/"logger" - the tracing/auditing story is sensible! :-)
