### DISCUSSION TITLE
Load defaults with configvars and keep defined parser arguments

### DISCUSSION THREAD

**Discussion by yt-invers** [pypyr/pypyr#311] [Q&A] [answered]
I try to load defaults from a yaml file (i know the defaults step), but to keep my cli arguments.
This would overwrite the cli argument `play` with the one defined inside the configvars file.

```
context_parser: pypyr.parser.keyvaluepairs

steps:
  - pypyr.steps.configvars
  - name: pypyr.steps.echo
    in:
      echoMe: '{play}'
```
An unfortunately wrong solution from ChatGPT. Exists something like this in another form?
![Screenshot from 2022-12-12 13-05-56](https://user-images.githubusercontent.com/114144546/207258352-e1fd1bf0-79c0-4bbb-8839-d46212617b89.png)

**Comment by yaythomas** [comment, marked as answer]
Goodness, I don't even know where ChatGPT would have got that from! I don't recognise the flag name at all! (If someone somewhere wrote some extension like this, feel free to get in touch!)

Yes, you're right @yt-invers, `pypyr.steps.configvars` will always overwrite on update - so it will overwrite cli arguments.

Configvars does a bit more than just loading from yaml - it interacts with the pypyr config system, checks multiple file locations and also pyproject.toml.

If you're happy just to load from a specific yaml file, you can do this:
```yaml
context_parser: pypyr.parser.keyvaluepairs
steps:
  - name: pypyr.steps.fetchyaml    
    in:
      fetchYaml:
        path: my-file.yaml
        key: defaults
  - pypyr.steps.default
  - name: pypyr.steps.echo
    in:
      echoMe: '{play}'
```

In this case your yaml file will look like this (note to `vars` parent key here, since we're directly loading the yaml, it's not going via the config system):
```yaml
# ./my-file.yaml
play: set in yaml
```

The magic here is that the `fetchYaml` step is pumping the values from yaml into the `defaults` key, pre-filling it for the `default` step that comes next. The default step will then only write values from the `defaults` key to the context root if they don't exist yet.

The net result is that it you will keep your CLI arguments - i.e the CLI argument will always take precedence over the yaml file values.

You can achieve the same sort of idea using `configvars`, as long as you save you "defaults" under a `defaults` key in the config file:

```yaml
# ./pypyr-config.yaml
vars:
  defaults:
    play: set in yaml in config file
```

and the pipeline:
```yaml
context_parser: pypyr.parser.keyvaluepairs
steps:
  - pypyr.steps.configvars
  - pypyr.steps.default
  - name: pypyr.steps.echo
    in:
      echoMe: '{play}'
```

Doing it like this means you could set your `play` value in any valid pypyr config source, for example pyproject.toml:
```toml
# ./pyproject.toml
[tool.pypyr.vars.defaults]
play = "from pyproject.toml"
```

But you raise a good point, this is a frequent use-case: use cli args as an override for a set of defaults. Although you can achieve this using the code above, to interact with the pypyr config system natively we should probably add a `configvarsdefault`* step or similar that only sets values if they don't exist already.


*not the world's greatest name 🤔
