### ISSUE TITLE
helpers for py strings

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#110]
Create helper functions that are directly available to py strings.

Specifically:
* hasvalue(thing)
* exists(thing)

Add new module for eval expression helpers. Add this module's vars to the eval global namespace.

this is useful because currently pipers have to jump through hoops on run bool conditions on existence checks(you get an error if the var doesn't exist in context) and on truthy style checks on strs (str that exists but is not literal "true" will be resolve false because the pypyr core tries to be too helpful with converting strings to bools by evading True/True/1 et as bool True and everything else False).

**Comment by Reskov** [comment]
Does not
```!py "'key' in locals()"```
do the trick with existence check?

**Comment by 345thomas** [comment]
It does indeed, you're very right!

The idea was to make it "easier" on non-code-y pipeline authors, but I'm not all that convinced it's "easier" yet...

**Comment by yaythomas** [comment]
Instead of having to hand-code helpers, allow operators to specify imports for py strings.

e.g, to use pathlib or math, allow operator:

```yaml
- name: pypyr.steps.pyimport
   in:
     pyImport:
       import math 
       from pathlib import Path

- name: pypyr.steps.contextsetf
   in:
     contextSetf:
         mathy: !py math.ceil(5)
         paths: !py Path('/blah').exists()
```

Allow for aliases - i.e import of the form:

```python
import arb as alias
from arb import one as onealias, two as twoalias
```

This will be backwards compatible with all existing py strings, since it's opt-in to import namespace like this.
