### ISSUE TITLE
pypyr.steps.contextsetif

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#112]
Works similar to contextsetif, but allow a ternary construct where `if x then b: value else b: othervalue`

```
    contextsetif:
      set: 
        blah: blahvalue
      if: boolhere
      else:
        blah: alternate 
```
