### ISSUE TITLE
flat & recursive string formatting specifiers

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#195]
```yaml
k1: v1
k2: '{k1}'
k3: '{k2}'
k4: 'k3 substitutes to {k3} and k2 to {k2}'
k5: 123
k6: '{k5}'
k7:
  - 123
  - 456
  - '{k2}'
```

String substitution expressions at present default to this:
1. For a string with multiple {formatting expressions}, will not recurse nested expressions. Thus `'{k4}' == 'k3 substitutes to {k2} and k2 to {k1}'`
2. For a value that contains one and only one formatting expression and nothing else, will recurse nested expressions AND keep the resolved type (i.e not cast to string). Thus 
2.1 `'{k6}' == 123`
2.2 `'{k7}' == [123, 456, 'v1']`

Add Recursive Format `rf` and Flat Format `ff` specifiers, so that:
- `'k3 substitutes to {k3:rf} and k2 to {k2}' == 'k3 substitutes to v1 and k2 to {k1}'`
- `'{k7:ff}' == [123, 456, '{k2}']`

Maintain backwards compatibility so the default behaviour stays the same.
