### ISSUE TITLE
bare assert

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#196]
`pypyr.steps.assert` to support all 3 inputs:

```yaml
assert: truthy me

assert:
  this: truthy me

assert:
  this: compare me
  equals: to this
```

Currently on the last two supported. Added the bare assert form `assert: eval-me-as-truthy` saves on typing and is backwards compatible with specific check on input which form it is.
