### ISSUE TITLE
jsonify - convert context to json string

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#197]
Add `!jsonify` tag that will parse a context structure to a json string.

```
- name: pypyr.steps.contextsetf
   in:
     contextSetf:
       my_json_string: !jsonify
         k1: v1
         k2: 123
```

Results in `my_json_string` == `'{"k1": "v1", "k2": 123}'`

Do substitutions/string interpolation on input.

This will be handy for REST api calls where you want to work with context, but serialise the result to a json string to pass to the API.
