### ISSUE TITLE
simplify pypyr.steps.py syntax

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#204]
working with context in a `pypyr.steps.py` step means working with the dict object rather than its contents:

```yaml
    - name: pypyr.steps.py
      description: runs arb python
      in:
        # multi-line statement starts with |, per yaml spec
        pycode: |
                  print(f"py step: {0+1}")
                  context['arbvalue'] = 6
                  print(context['arbvalue'])
```

Add `py` mode of execution where pipeline authors don't need to trip over the `context['arbkey']` syntax and can just use `arbkey`:

```yaml
    - name: pypyr.steps.contextsetf
      comment: set arb context to manipulate in the next step
      in:
        contextSetf:
          existing_key: existing value
          existing_dict:
            a: a value
            b: 123

    - name: pypyr.steps.py
      description: runs arb python
      in:
        # multi-line statement starts with |, per yaml spec
        py: |
          from math import sqrt
          print(f"py step: {1+1}")
          
          arbvalue = sqrt(1764)
          print(int(arbvalue))

          existing_key = 'updated value'
          existing_dict['a'] = 'a value set in py step'
          existing_dict['b'] = 456
```

Make this backwards compatible so pipeline author can use either `pycode` or `py` inputs. Additionally, there might be occasions where access to the dict object itself is useful, rather than just its contents.
