### ISSUE TITLE
python executable path

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#265]
Add custom step that gets `sys.executable` and writes this result to a `{python}` context property.

Reason being that when running python as a sub-process on particularly Windows, due to various vagaries of the Windows API & python executable redirector, it will not necessarily call the correct python run-time - e.g call the system python instead of the currently active venv's python.

Therefore Python docs recommend when invoking python as a subprocess (e.g as in the `pypyr.steps.cmd` step) you use the full path to the executable and NOT to rely on $PATH resolving where you think it should.

This will allow step authors to do this:
```yaml
- name: pypyr.steps.cmd
   comment: won't work on windows
   in:
     cmd: python -m blah.blah

- name: pypyr.steps.cmd
   comment: assuming python contains full path to python executable, will work everywhere.
   in:
     cmd: '{python} -m blah.blah'
```

For more info, see https://bugs.python.org/issue42041
