### ISSUE TITLE
shortcuts

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#267]
Now that pypyr has a cross-platform config system #251, allow operators to create cli shortcuts to pipelines & args in the config file.

The reason is to save on typing on frequent pypyr runs in the same repo, where you might have:

```terminal
$ pypyr arb/my-pipeline --log 20 arg1=1234 arg2="/path/to long/annoying path to type/x" arg3="\narb'hello"
```

If in config you can create a shortcut like this:
```yaml
shortcuts:
  my-shortcut:
    pipeline: arb/my-pipeline
    args:
      arg1: 1234
      arg2: /path/to long/annoying path to type/x
      arg3: "\narb'hello"
    log: 20
```

You can now run from the cli:
```console
$ pypyr my-shortcut
```

and it will run the pipeline with the saved inputs from configuratiion without having to type/retrieve long/complex chain of input args.

This will allow operators to create multiple shortcuts to different pipelines or the same pipeline with different inputs - and easily execute these saved configurations from the cli.

Operators will also be able to create user-specific or global (machine-wide) config - allowing operator to execute a "global" shortcut from anywhere on the system regardless of current directory.

Great thanks to  @jmitchel3 from @codingforentrepreneurs for the great idea! 🙌 🙌
