### ISSUE TITLE
cmd step: support ~ & env

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#270]
`pypyr.steps.cmd` doesn't support ~ expansion or $ENV vars in its cmd input.

Easy enough to add. Then operators won't have to go and invoke the more inefficient `pypyr.steps.shell` just for doing something like:

```yaml
- name: pypyr.steps.cmd
   in:
     cmd: cp ~/mypath ~/myoutpath
```

Note that $ENV expansion supports formats `$ENV` and `${ENV}`. It leaves unrecognised tokens alone, meaning pypyr can do a {substitution} format afterwards without breaking anything.
