### ISSUE TITLE
cmdOut simplify format string

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#272]
cmdOut on cmd/shell step is currently a dict, where:

```dict
out = {
    'returncode': completed_process.returncode,
    'stdout': stdout,
    'stderr': stderr
}
```

This leads to formatting expressions using the code like this:
```yaml
- name: pypyr.steps.echo
  run: !py "cmdOut['returncode'] == 0"
  in:
    echoMe: "you'll only see me if cmd ran successfully with return code 0.
            the command output was: {cmdOut[stdout]}.
            the error output was: {cmdOut[stderr]}."
```

This is unnecessarily verbose with all the [] for keyed access.

Make a SubProcessResult class for cmdOut to allow a dotted accessor like this:
```yaml
- name: pypyr.steps.echo
  run: !py cmdOut.returncode == 0
  in:
    echoMe: "you'll only see me if cmd ran successfully with return code 0.
            the command output was: {cmdOut.stdout}.
            the error output was: {cmdOut.stderr}."
```

Make this change backwards compatible so __get_item__ look-up on class still works too.
