### ISSUE TITLE
switch (aka if-elif branching)

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#298]
Add `switch` step to allow switch case style if/elif branching on step-groups:

```yaml
  - name: pypyr.steps.switch
    in:
      switch:
        - case: True
          call: A
        - case: False
          call: never
        - default: B
```

switch will run the 1st `case` that evaluates `True`. No fall-through - i.e explicit `break` not necessary.

`default` is optional. If it exists, will run only if all `case` above evaluates `False`.

`call` specifies the step-group to call if `case` is True. It can also be in expanded format:

```yaml
call:
  groups: ['sg1', 'sg2'] # run sg1 and sg2 serially
  success: 'sg'
  failure: 'fg'
```

Upon completion of switch, execution resumes at the next step of the pipeline.
