### ISSUE TITLE
run_failure_step_group: Object of type Exception is not JSON serializable

### ISSUE THREAD

**Issue by joenatan** [pypyr/pypyr#308]
when I raise a ValueError or any other Exception in a python module, the following error appears in the on_failure handler:

- ERROR:pypyr.stepsrunner:run_failure_step_group: Failure handler also failed. Swallowing.
- ERROR:pypyr.stepsrunner:run_failure_step_group: Object of type Exception is not JSON serializable

How can raise an error in python modules that works in the failure handler?

**Comment by yaythomas** [comment]
hi @joenatan, could you help me understand what's exactly is giving you the problem? I'm having a hard time reproducing the error.

You can raise an error like this:
```yaml
steps:
  - name: pypyr.steps.py
    in:
      py: raise ValueError('arb')

on_failure:
  - name: pypyr.steps.echo
    in:
      echoMe: hello {runErrors}
```

Or in a custom step you do this:
```yaml
def run_step(context):
    raise ValueError('arb from custom step')
```

if you could please share some example code + pipeline that's causing the problem that would help me a lot!
