### ISSUE TITLE
load

### ISSUE THREAD

**Issue by yaythomas** [pypyr/pypyr#57]
run this step x iterations across y threads, or
run this step repeatedly for x time across y threads

**Comment by Reskov** [comment]
Is any deadline for this feature?

My imagination draw me following step layout
```yaml
steps:
  - name: my.package.another.module
    async: 5 # (default: 0 - sync/blocking run, 1 async run, greater than 1 make sense only when used foreach or while loop)
    register: context_key_name # (Required if async > 0, set step instance to context, step have list of running coroutines)
    timeout: 5 # (default 0, max timeout for running all coroutines, will cancel coroutines silently, but wait_for should raise exception if shallow is false)
  
    while:
      stop: '{keyhere}'
      blocking: True # default True, wait_for after each step, but conflicts with async property (async > 1 does not make sense if blocking is on), probably should warn about it...

  - name: pypyr.steps.wait_for
    description: special step to wait until previous async step is finished or cancelled.
    in:
        wait_for:
            - step: context_key_name
```

Does it make sense? May I try to implement this approach and share results? 

If `wait_for` wasn't called directly, should we wait or cancel all pending coroutines at the end of pipeline?

**Comment by 345thomas** [comment]
No deadline, no. This is actually one of the trickier ones, and it requires careful thought and consideration given its potential for introducing regression issues, knock-on impact on consumers and downstream plug-ins. I also find myself having to balance what a pipeline _is_, conceptually - as a sequence of steps. 

What you're effectively doing here is allowing a step to run non-blocking, or async, meaning it will move on to the next step immediately, or until you, like you're also wondering about: 
> If wait_for wasn't called directly, should we wait or cancel all pending coroutines at the end of pipeline?

So there are really two separate things here:
1. run step non-blocking
2. run step over multiple co-routines (similar to `while`, but in parallel)

Conceptually, I've done similar to 1. previously - look at [waitfor in pypyraws](https://github.com/pypyr/pypyr-aws#pypyraws-steps-waitfor) as an example. This steps waits for an external process to finish that was initiated by any given previous non-blocking "async" step. The difference is that it's not the pypyr core that's async, it's actually up to the step to initiate a non-blocking async process. 

So, let's say you're doing an expensive long-running operation. That goes in a step called `mypypyrplugin.steps.longrunningoperation`. This step contains code that kicks off this long running operation but returns success to the pypyr core run-time immediately, so pypyr moves on to the next pipeline steps. 

Then there's another step for `mypypyrplugin.steps.waitforlongrunningoperationtofinish" that will poll whatever status needs to be polled (existence of file, web-service response, whatever it is) and block until it receives the result it's waiting for.

I know I'm not fully answering your question yet, and I'm sorry about that, just letting you know in the meantime where my thoughts are and I'm still thinking about it!

**Comment by 345thomas** [comment]
p.s if this is just about invoking the pypyr core from your aiohttp stack, you can still run the pypyr run_pipeline sync methods without blocking using something similar to this https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

**Comment by Reskov** [comment]
Yeap, `run_in_executor` probably will do the trick, thanks for the suggestion, but it's a little bit silly to my mind, because I will need to have support for both async/sync libraries, for example I can't use HTTP client from `aiohttp` at blocking `run_step` function. And it is a big deal for me, I have many other asynchronous libraries, db, redis, our sdk for internal services. Of course they may be rewritten/replaced to use as synchronous, but it wouldn't be so easy.

 For now, I found a tricky workaround https://gitlab.com/pgjones/quart/blob/master/quart/flask_patch/_patch.py#L20 , this code part allow to run async coroutine from sync code, but that is monkey-patch of loop, and as result break support for `uvloop`. And potentially may be not compatible with even minor python releases.

From the other side I'm started experimenting to support both `async def run_step(context)` and original `def run_step(context)` for step modules. And seems it is working fine.

I create a wrapper function, which ensure that coroutine result was awaited

```python
async def ensure_future_result(result):
    if asyncio.iscoroutine(result):
        return await result
    return result
```
and use it inside `Step` class

```
await ensure_future_result(self.module.run_step(context))
```

You may look inside my fork if you interested, Reskov@06326e912c8f58ebdbbc9e95a259611507319bb3, **all unit tests and flake checks are already passed**, but as you mention, this does not guarantee that I will not break the back compatibility for plugins, therefore regression of course is needed.
Also I agree with that almost all async stuff may be done running step synchronously, and seems it fairly enough to work with pipeline like `script` executor.

I probably need to re-think about my expectations, if you will find my experiment reasonable (it may helps with future threads decision) ping me here, I will add some test cases and prepare PR.
p.s. Sorry to bother you with my problems, I'm appreciate your help, and I'm really love your library, it seems at most fits all my needs

**Comment by 345thomas** [comment]
Hi Reskov,

I checked out your fork - it's looking good! Sorry I've taken a bit of time to respond, I've been thinking it through carefully.

I get what you're saying for your use-case, and thank you for explaining more, it's very helpful for me to understand better - invoking the pypyr api async to sync it up with the top loop with `get_event_loop`  or `asyncio.run` makes everything downstream work async too without a fuss, especially when you're invoking other apis in your steps.

I'm not too cheerful about the async creep all the way up and down through the api, though, where for almost all of there aren't actually any suspend points in the pypyr core meaning the code is going to be running synchronously anyway, until such time as it gets to a step that actually does something async (an `aoihttp` call, say). . . 

And it feels like it's going to lead to trouble when there's fundamentally synchronous/non-async-friendly code sitting in a step's run_step, being invoked from an async core. I get in your particular case your'e going to make sure that this does _not_ happen, but other pypyr consumers are not necessarily going to get the expected results. Especially where sub-processes kick of (e.g the shell/safe-shell steps).

So while your `ensure_future_result` function is a nifty bit of code, I think it'll end up causing surprises for downstream step authors/consumers.

Assuming the pypyr core is invoked synchronously (i.e no top event loop exists already), individual steps are then free to do an `async.run()` when and where they see fit - i.e a step can do an async invoke easily enough to call `aoihtttp` asynchronously, without affecting other steps or the pypyr core.

> Also I agree with that almost all async stuff may be done running step synchronously, and seems it fairly enough to work with pipeline like script executor.

Yes, you've hit the nail on the hit! Pretty much all of pypyr is really wedded into the world of scripting - it's memory hungry, it makes no attempt to streamline/optimize code for the purposes of a lean and mean web-server, which is why making it behave async within the context of a web-server process is probably not going to be something the web-server will be too happy about. Off-loading memory/cpu/io hungry code like pypyr onto a queue or outside processor like an aws step function is going to make the web-server a lot happier, and then the core can happily stay doing what it's doing synchronously, while allowing individual step authors to code async functionality as appropriate when doing things like I/O or high latency calls.

So I'm very unlikely to merge this into the core, sorry!

Incidentally, not that this helps you any 😄 , the parallel functionality that I was planning on this load task, is going to be more something like this:
```
- name: pypyr.steps.echo
    description: loop 5 times
    in:
      echoMe: "this is step {whileCounter} of 5, all running in parallel."
    while:
      parallel: true
      max: 5
```
